// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/db.ts";
import * as $1 from "./routes/api/session_routes.ts";
import * as $2 from "./routes/controllers/sessions.ts";
import * as $3 from "./routes/db.ts";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/server.ts";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/api/db.ts": $0,
    "./routes/api/session_routes.ts": $1,
    "./routes/controllers/sessions.ts": $2,
    "./routes/db.ts": $3,
    "./routes/index.tsx": $4,
    "./routes/server.ts": $5,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
